### ISSUE TITLE
API 통신을 위한 dataflow 구축

### ISSUE THREAD

**Issue by Kick-snare** [K-hackathon-problemSolver/MyOrder#8]
### TODO

- [x] Retrofit gradle 추가 
- [ ] store DTO 작성
- [ ] retrofit  api interface 작성
- [ ] domain에 repo 인터페이스 작성
- [ ] data에 repo 구현체 작성
- [ ] storeList에 필요한 usecase에 injection 될 수 있도록 di 작성
